[package]
name = "undo"
version = "0.1.17"
edition = "2024"
rust-version = "1.85"
description = "Give your files an undo button"
repository = "https://github.com/treadiehq/undo"
homepage = "https://github.com/treadiehq/undo"
readme = "README.md"
license-file = "LICENSE"
keywords = ["filesystem", "history", "snapshot", "restore", "undo"]
categories = ["command-line-utilities", "filesystem", "development-tools"]

[dependencies]
clap = { version = "4", features = ["derive"] }
notify = "6"
rusqlite = { version = "0.31", features = ["bundled"] }
semver = "1"
sha2 = "0.10"
flate2 = "1"
chrono = { version = "0.4", features = ["clock"] }
walkdir = "2"
similar = "2"
signal-hook = "0.3"
dirs = "5"
anyhow = "1"
libc = "0.2"
ignore = "0.4.25"
toml = "0.8"
serde = { version = "1", features = ["derive"] }
tempfile = "3"
