use anyhow::Result;
use flate2::Compression;
use flate2::read::GzDecoder;
use flate2::write::GzEncoder;
use std::fs;
use std::io::{Read, Write};
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

pub const MAX_SNAPSHOT_SIZE: usize = 100 * 1024 * 1024; // 100 MB

/// Process-wide counter giving each in-flight temp file a unique name, so the
/// parallel initial scan can have several workers writing distinct snapshots
/// (or even the same hash) at once without colliding on a shared `.gz.tmp` path.
static TMP_SEQ: AtomicU64 = AtomicU64::new(0);

fn snapshot_dir_in(base: &Path, project_id: i64) -> Result<PathBuf> {
    use std::os::unix::fs::DirBuilderExt;
    let dir = base.join("snapshots").join(project_id.to_string());
    fs::DirBuilder::new()
        .recursive(true)
        .mode(0o700)
        .create(&dir)?;
    Ok(dir)
}

fn snapshot_dir(project_id: i64) -> Result<PathBuf> {
    snapshot_dir_in(&crate::backtrack_dir()?, project_id)
}

/// Full filesystem path for a snapshot identified by content hash.
pub fn snapshot_path(project_id: i64, hash: &str) -> Result<PathBuf> {
    Ok(snapshot_dir(project_id)?.join(format!("{}.gz", hash)))
}

/// Compress and store file content under an explicit data-dir `base`. Returns the
/// path string for DB storage. Deduplicates automatically — if a snapshot with the
/// same hash exists, skips the write.
///
/// Taking `base` explicitly (rather than resolving `backtrack_dir()` internally)
/// lets the parallel initial scan call this from worker threads, which do not
/// inherit the test data-dir thread-local override.
///
/// NOT durable: no `fsync`. This is the initial-scan path, which writes up to
/// `MAX_FILES_DEFAULT` snapshots and would be crippled by a per-file fsync. Scan
/// snapshots don't need power-loss durability anyway — the source file still
/// exists on disk, so a lost snapshot is regenerated by the next scan. The live
/// path uses `save` (durable) for content that may not survive on disk.
pub fn save_in(base: &Path, project_id: i64, hash: &str, content: &[u8]) -> Result<String> {
    write_snapshot(base, project_id, hash, content, false)
}

/// Compress and store file content, durably. Returns the path string for DB
/// storage. Deduplicates automatically — if a snapshot with the same hash exists,
/// skips the write.
///
/// Durable (`fsync` of the temp file before rename + `fsync` of the snapshot
/// directory after rename) so a committed `file_events` row can never end up
/// pointing at a snapshot whose bytes (or whose rename) did not survive a power
/// loss. Used by the live per-event handlers, where each capture may hold content
/// that no longer exists anywhere else on disk — unlike the regenerable initial
/// scan, which deliberately skips fsync for throughput.
pub fn save(project_id: i64, hash: &str, content: &[u8]) -> Result<String> {
    write_snapshot(&crate::backtrack_dir()?, project_id, hash, content, true)
}

/// Shared snapshot writer. `durable` selects whether the write is forced to disk
/// (`fsync` the file before rename, then `fsync` the parent directory so the
/// rename itself survives a crash). See `save` / `save_in` for why the live and
/// scan paths choose different answers.
fn write_snapshot(
    base: &Path,
    project_id: i64,
    hash: &str,
    content: &[u8],
    durable: bool,
) -> Result<String> {
    let dir = snapshot_dir_in(base, project_id)?;
    let path = dir.join(format!("{}.gz", hash));
    if !path.exists() {
        // Write to a uniquely-named temp file then rename atomically. POSIX
        // guarantees rename is atomic on the same filesystem, so a crash mid-write
        // can never leave a partial file at the final path that would be mistaken
        // for a valid snapshot. The unique suffix keeps concurrent writers of the
        // same hash from racing on a shared temp path.
        let seq = TMP_SEQ.fetch_add(1, Ordering::Relaxed);
        let tmp = path.with_file_name(format!("{}.gz.tmp.{}.{}", hash, std::process::id(), seq));
        let _ = fs::remove_file(&tmp); // remove stale temp if present
        let write_result = (|| -> Result<()> {
            use std::os::unix::fs::OpenOptionsExt;
            let file = fs::OpenOptions::new()
                .write(true)
                .create_new(true) // O_CREAT | O_EXCL — refuses to follow symlinks
                .mode(0o600)
                .open(&tmp)?;
            let mut encoder = GzEncoder::new(file, Compression::fast());
            encoder.write_all(content)?;
            // `finish` flushes the gzip stream and hands back the inner file so we
            // can fsync it before the rename when durability is requested.
            let file = encoder.finish()?;
            if durable {
                file.sync_all()?;
            }
            fs::rename(&tmp, &path)?;
            if durable {
                // fsync the directory so the rename (a metadata op) is itself
                // durable — otherwise a power loss could lose the rename even
                // though the file contents reached disk. Best-effort: a directory
                // that can't be opened/synced doesn't fail the snapshot.
                if let Ok(dir_file) = fs::File::open(&dir) {
                    let _ = dir_file.sync_all();
                }
            }
            Ok(())
        })();
        if write_result.is_err() {
            let _ = fs::remove_file(&tmp); // clean up any partial temp file
        }
        write_result?;
    }
    Ok(path.to_string_lossy().to_string())
}

/// Load and decompress a snapshot, returning the original file content.
/// Caps decompressed output at `MAX_SNAPSHOT_SIZE` to prevent gzip bombs.
pub fn load(project_id: i64, hash: &str) -> Result<Vec<u8>> {
    let path = snapshot_path(project_id, hash)?;
    let file = fs::File::open(&path)
        .map_err(|e| anyhow::anyhow!("snapshot not found ({}): {}", hash, e))?;
    let decoder = GzDecoder::new(file);
    let mut content = Vec::with_capacity(8192);
    let limit = MAX_SNAPSHOT_SIZE as u64 + 1;
    let n = decoder.take(limit).read_to_end(&mut content)?;
    if n as u64 >= limit {
        anyhow::bail!(
            "snapshot {} decompresses beyond {} limit — refusing to load",
            hash,
            MAX_SNAPSHOT_SIZE,
        );
    }
    Ok(content)
}

/// Count snapshot files on disk for a project.
pub fn count(project_id: i64) -> Result<usize> {
    let dir = crate::backtrack_dir()?
        .join("snapshots")
        .join(project_id.to_string());
    if !dir.exists() {
        return Ok(0);
    }
    Ok(fs::read_dir(dir)?.filter_map(|e| e.ok()).count())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Content saved to a snapshot is recovered byte-for-byte on load.
    #[test]
    fn save_and_load_round_trip() {
        let data_dir = tempfile::tempdir().unwrap();
        crate::set_test_data_dir(data_dir.path().to_path_buf());

        let content = b"hello, snapshot world\n";
        save(1, "roundtrip_hash", content).unwrap();
        let loaded = load(1, "roundtrip_hash").unwrap();
        assert_eq!(loaded, content);
    }

    /// Saving the same hash twice must not corrupt the snapshot or create duplicate files.
    #[test]
    fn save_is_idempotent_for_same_hash() {
        let data_dir = tempfile::tempdir().unwrap();
        crate::set_test_data_dir(data_dir.path().to_path_buf());

        let content = b"duplicate content to save twice";
        save(1, "dedup_hash", content).unwrap();
        // Second call must succeed — path.exists() guard skips the write.
        save(1, "dedup_hash", content).unwrap();
        let loaded = load(1, "dedup_hash").unwrap();
        assert_eq!(loaded, content);
    }

    /// Loading a hash with no backing file returns a clear error rather than panicking.
    #[test]
    fn load_nonexistent_hash_returns_error() {
        let data_dir = tempfile::tempdir().unwrap();
        crate::set_test_data_dir(data_dir.path().to_path_buf());

        let result = load(1, "this_hash_does_not_exist_xyz");
        assert!(result.is_err());
        let msg = result.unwrap_err().to_string();
        assert!(msg.contains("snapshot not found"), "got: {}", msg);
    }

    /// Both the durable live path (`save`) and the fast scan path (`save_in`)
    /// must produce a valid, identical, loadable snapshot for the same content.
    /// Locks in the durability refactor: the only intended difference between the
    /// two is the fsync, never the bytes written or the dedup behaviour.
    #[test]
    fn durable_and_nondurable_writes_round_trip_identically() {
        let data_dir = tempfile::tempdir().unwrap();
        crate::set_test_data_dir(data_dir.path().to_path_buf());
        let base = crate::backtrack_dir().unwrap();

        let content = b"content written via both paths";
        // Durable live path.
        save(7, "durable_hash", content).unwrap();
        // Fast scan path (explicit base, no fsync).
        save_in(&base, 7, "scan_hash", content).unwrap();

        assert_eq!(load(7, "durable_hash").unwrap(), content);
        assert_eq!(load(7, "scan_hash").unwrap(), content);

        // Re-saving an existing hash via the durable path stays idempotent.
        save(7, "durable_hash", content).unwrap();
        assert_eq!(load(7, "durable_hash").unwrap(), content);
    }

    /// count() reflects the number of distinct saved snapshots and is unaffected by deduplication.
    #[test]
    fn count_returns_correct_number_of_snapshots() {
        let data_dir = tempfile::tempdir().unwrap();
        crate::set_test_data_dir(data_dir.path().to_path_buf());

        assert_eq!(count(42).unwrap(), 0, "no snapshots yet");
        save(42, "hash_a", b"content a").unwrap();
        assert_eq!(count(42).unwrap(), 1);
        save(42, "hash_b", b"content b").unwrap();
        assert_eq!(count(42).unwrap(), 2);
        // Saving the same hash again must not increase the count (deduplication).
        save(42, "hash_a", b"content a").unwrap();
        assert_eq!(count(42).unwrap(), 2);
    }
}
